[cantfind]
isContextEnabled = true
content = """
# Couldn't find any videos for you!
This error means we couldn't find a video, we simply do not have it. 
Everything still shows up in search results, but that doesn't neccesarily mean we actually have a video of it.
"""

[addthis]
isContextEnabled = true
content = """
# Can you add X / When will Y be added?
Movie-web doesn't host its own content, and thus we do not know when something will be added, nor can we add something ourselves. 

Think of movie-web like google, we search the web for videos but we don't add our own, we only allow people to search.
"""

[legal]
isContextEnabled = true
content = """
# Where does our content come from? Is it legal?
We take the content directly from other sites that host content. We do not own any of the files. We simply display what we find on other sites.

Think of it like Google, we search the Internet for videos, but we dont own the sites, nor the content. We merely link to them.

Thus, the legality of watching the video depends on what sites it took from. We do not control that however. You can check the source section of the video settings to see what site you're watching from.
"""

[cantdownload]
isContextEnabled = true
content = """
# How to download?
Under the settings cog in the video player, you can find the download setting.

**If the option mentions downloading a playlist, then you'll be downloading a HLS playlist, you can play this file using VLC.**
Currently, the only sources that support downloading an MP4 file are Showbox and HDrezka. Both are accessible via extension, with Showbox also being available through a non-Cloudflare proxy.
"""

[episodes]
isContextEnabled = true
content = """
# How can I change episodes or seasons?
To switch which episode you're watching, you can click the [button](https://media.discordapp.net/attachments/871713465578979351/1135095318036353105/image.png) shown below in the video player. 
To change seasons, you click the same button as before, but then click the arrow top left of the popup.
"""

[dubs]
isContextEnabled = true
content = """
# Can I play this movie or TV show in another language?
It's not possible to watch content in other languages on movie-web. We don't intend to add this feature soon, so you're most likely better off searching for a website that provides content in your desired language!
Here is a list of non-English sites: <https://fmhy.pages.dev/non-english>
Find your language in the sidebar and look under the Streaming section. [Use this adblocker!](<https://ublockorigin.com>)
"""

[apps]
isContextEnabled = true
content = """
# Where is the app download?
There is a work-in-progress mobile app, get the Updates role to be notified!
On supported instantes, you can install the website as a [PWA](https://cdn.discordapp.com/attachments/656888828430385171/1174969037403459624/IMG_4763_1.PNG) on mobile devices:
[iOS guide](<https://www.wikihow.com/Install-Web-Apps-on-iPhone-or-iPad>)
[Android guide](<https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&oco=1>)
"""

[v5]
isContextEnabled = true
content = """
# When will v5 come out?
We don't know. We're working on it, but we don't have a release date yet:tm:.

You can check the planned features and their status [here](https://github.com/orgs/movie-web/projects/2).
If you're a developer and want to help, you can ask to be assigned to an issue on GitHub.
"""

[theatre]
isContextEnabled = true
content = """
# Why can't I watch this movie yet?
The movie you are trying to watch only came out in theatres very recently. We don't control our content, and it is not possible for us to show movies that haven't come out on streaming yet. 
"""

[instances]
isContextEnabled = true
content = """
# Why is movie-web.app down/having an issue?
The old official instance has been taken down. You can read more [here](https://discord.com/channels/871713465100816424/1116430057922121760/1210364442601193552) and in <#871715205686636564>
You may still be seeing a cached version in your browser, but it is outdated, unsupported and will dissapear soon.

To keep using an updated movie-web, switch to a [Community Instance](https://movie-web.github.io/docs/instances) or [self-host]https://movie-web.github.io/docs/self-hosting/hosting-intro>)
"""

[dns]
isContextEnabled = true
content = """
# Why is my search/other not working?
We search using TMDB, but your ISP or network could be blocking the website.

If that is the case, you can [set your dns to 1.1.1.1](https://developers.cloudflare.com/1.1.1.1/setup/), use a VPN, or use [WARP](<https://1.1.1.1>)
"""

[showbox]
isContextEnabled = true
content = """
# Why isn't showbox working?
showbox blocks Cloudflare IPs, so a non-cloudflare proxy (or extension) must be used. (selfhosters: use Netlify)
All [Community Instances](<https://movie-web.github.io/docs/instances>) should have a non-cloudflare proxy by default.
"""

[extension]
isContextEnabled = true
content = """
# How do I get all the sources?
We have an [open source](https://github.com/movie-web/extension) extension available to unlock more sources.
You can install it on desktop browsers, and on Android Firefox.
"""
